

movement_csv: "/mnt/data/NatureNet/Hammerhead_In/Data_aniMotum_CTCRW_output_predicted_rerouted_non-projected_with_Argosfilter_data.csv"

grid_res_lon: 0.27 #0.027
grid_res_lat: 0.27 #0.027
out_dir: "/mnt/data/NatureNet_Env/output"
run_uid: "batymetry_only"

n_clusters: 40
df_run_uid: "hammerhead_v1"
df_dir: "/mnt/data/NatureNet/Hammerhead_Out_v1/"

init_preprocess: False

