datetimes:
- 14072024T00:00:00Z
- 15072024T00:00:00Z
- 16072024T00:00:00Z
- 17072024T00:00:00Z
- 18072024T00:00:00Z
- 19072024T00:00:00Z
- 20072024T00:00:00Z
- 21072024T00:00:00Z
- 22072024T00:00:00Z
- 23072024T00:00:00Z
- 24072024T00:00:00Z
- 25072024T00:00:00Z
- 26072024T00:00:00Z
- 27072024T00:00:00Z
- 28072024T00:00:00Z
- 29072024T00:00:00Z
- 30072024T00:00:00Z
- 31072024T00:00:00Z
- 01082024T00:00:00Z
- 02082024T00:00:00Z
- 03082024T00:00:00Z
- 04082024T00:00:00Z
- 05082024T00:00:00Z
- 06082024T00:00:00Z
- 07082024T00:00:00Z
- 08082024T00:00:00Z
- 09082024T00:00:00Z
- 10082024T00:00:00Z
- 11082024T00:00:00Z
- 12082024T00:00:00Z
- 13082024T00:00:00Z
- 14082024T00:00:00Z
df_dir: /mnt/data/NatureNet/Hammerhead_Out_v1/
df_run_uid: hammerhead_v1
final_grid_res_deg: 0.027
instruments:
  Bathymetry:
    data_config: ../../config/environment/bathymetry_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    multi_chan: false
    resample_config: ../../config/environment/bathymetry_resample_config.yaml
  Coastal_Dist:
    data_config: ../../config/environment/distance_to_coast.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    multi_chan: false
    resample_config: ../../config/environment/distance_to_coast_resample_config.yaml
  SSS:
    data_config: ../../config/environment/sss_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240714T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240715T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240716T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240717T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240718T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240719T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240720T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240721T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240722T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240723T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240724T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240725T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240726T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240727T1200Z_P20251014T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240728T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240729T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240730T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240731T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240801T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240802T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240803T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240804T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240805T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240806T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240807T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240808T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240809T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240810T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240811T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240812T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240813T1200Z_P20251015T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240814T1200Z_P20251015T0000Z.nc
    multi_chan: true
    resample_config: ../../config/environment/sss_resample_config.yaml
  SST:
    data_config: ../../config/environment/sst_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240714.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240715.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240716.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240717.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240718.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240719.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240720.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240721.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240722.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240723.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240724.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240725.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240726.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240727.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240728.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240729.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240730.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240731.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240801.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240802.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240803.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240804.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240805.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240806.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240807.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240808.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240809.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240810.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240811.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240812.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240813.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240814.nc
    multi_chan: true
    resample_config: ../../config/environment/sst_resample_config.yaml
n_clusters: 40
out_dir: /mnt/data/NatureNet_Env/output
run_env_gen: true
run_final_env_gen: false
run_uid: simple_env
save_intermediate_maps: false
save_prelim_scene_maps: false
scenes_by_uid: true
update_stats: false
