datetimes:
- 03012024T00:00:00Z
- 04012024T00:00:00Z
- 05012024T00:00:00Z
- 06012024T00:00:00Z
- 07012024T00:00:00Z
- 08012024T00:00:00Z
- 09012024T00:00:00Z
- 10012024T00:00:00Z
- 11012024T00:00:00Z
- 12012024T00:00:00Z
- 13012024T00:00:00Z
- 14012024T00:00:00Z
- 15012024T00:00:00Z
- 16012024T00:00:00Z
- 17012024T00:00:00Z
- 18012024T00:00:00Z
- 19012024T00:00:00Z
- 20012024T00:00:00Z
- 21012024T00:00:00Z
- 22012024T00:00:00Z
- 23012024T00:00:00Z
- 24012024T00:00:00Z
- 25012024T00:00:00Z
- 26012024T00:00:00Z
- 27012024T00:00:00Z
- 28012024T00:00:00Z
- 29012024T00:00:00Z
- 30012024T00:00:00Z
- 31012024T00:00:00Z
- 01022024T00:00:00Z
- 02022024T00:00:00Z
- 03022024T00:00:00Z
- 04022024T00:00:00Z
df_dir: /mnt/data/NatureNet/Hammerhead_Out_v1/
df_run_uid: hammerhead_v1
final_grid_res_deg: 0.027
instruments:
  Bathymetry:
    data_config: ../../config/environment/bathymetry_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    multi_chan: false
    resample_config: ../../config/environment/bathymetry_resample_config.yaml
  Coastal_Dist:
    data_config: ../../config/environment/distance_to_coast.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    multi_chan: false
    resample_config: ../../config/environment/distance_to_coast_resample_config.yaml
  SSS:
    data_config: ../../config/environment/sss_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240103T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240104T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240105T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240106T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240107T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240108T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240109T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240110T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240111T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240112T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240113T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240114T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240115T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240116T1200Z_P20250722T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240117T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240118T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240119T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240120T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240121T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240122T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240123T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240124T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240125T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240126T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240127T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240128T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240129T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240130T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240131T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240201T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240202T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240203T1200Z_P20250723T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240204T1200Z_P20250723T0000Z.nc
    multi_chan: true
    resample_config: ../../config/environment/sss_resample_config.yaml
  SST:
    data_config: ../../config/environment/sst_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240103.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240104.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240105.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240106.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240107.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240108.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240109.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240110.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240111.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240112.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240113.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240114.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240115.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240116.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240117.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240118.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240119.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240120.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240121.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240122.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240123.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240124.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240125.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240126.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240127.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240128.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240129.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240130.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240131.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240201.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240202.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240203.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240204.nc
    multi_chan: true
    resample_config: ../../config/environment/sst_resample_config.yaml
n_clusters: 40
out_dir: /mnt/data/NatureNet_Env/output
run_env_gen: true
run_final_env_gen: false
run_uid: simple_env
save_intermediate_maps: false
save_prelim_scene_maps: false
scenes_by_uid: true
update_stats: false
