

#TODO - auto config gen that matches up various time periods, etc.
# Standing assumption is that all inputs have same count of scenes
# Can work to optimize this later, if need be (i.e. some more static products will be re-used multiple times, etc.)

instruments:
 Bathymetry:
  data_config: "../../config/environment/batymetry_data_config.yaml"
  multi_chan: False
  filenames: [
['/opt/dlami/nvme/NatureNet_Env/Bath/gebco_2025_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif'], ['/opt/dlami/nvme/NatureNet_Env/Bath/gebco_2025_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif']]

  resample_config: "../../config/environment/bathymetry_resample_config.yaml"
  #encoder_conf: "NA"
 SSS: 
  data_config: "../../config/environment/"
  multi_chan: True
  filenames: []
  resample_config: "../../config/environment/sss_resample_config.yaml"
  #encoder_conf: "NA" 
 
 SST:
   data_config: "../../config/environment/sst_resample_config.yaml"
   multi_chan: True
   filenames: []
   resample_config: "../../config/environment/sst_resample_config.yaml"
   #encoder_conf: "NA" 
 Coatal_Dist:
   data_config: "../../config/environment/distance_to_coast.yaml"   
   multi_chan: False
   filenames: []
   resample_config: "../../config/environment/distance_to_coast_resample_config.yaml"

final_grid_res_deg: 0.027 #0.0108000108

datetimes: ['01062024T00:00:00Z', '02062024T00:00:00Z']

out_dir: "/opt/dlami/nvme/NatureNet_Env/output"

update_stats: True

save_prelim_scene_maps: True
save_intermediate_maps: True

run_uid: "batymetry_only"

#No encoder data streams??





