

#TODO - auto config gen that matches up various time periods, etc.
# Standing assumption is that all inputs have same count of scenes
# Can work to optimize this later, if need be (i.e. some more static products will be re-used multiple times, etc.)

instruments:
 Bathymetry:
  data_config: "../../config/environment/bathymetry_data_config.yaml"
  multi_chan: False
  filenames: [
['/mnt/data/NatureNet_Env/Bath/gebco_2025_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif'], ['/mnt/data/NatureNet_Env/Bath/gebco_2025_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif']]

  resample_config: "../../config/environment/bathymetry_resample_config.yaml"
  #encoder_conf: "NA"

final_grid_res_deg: 0.027 #0.0108000108

datetimes: ['01062024T00:00:00Z', '02062024T00:00:00Z']

out_dir: "/mnt/data/NatureNet_Env/output"

update_stats: False

save_prelim_scene_maps: True
save_intermediate_maps: True

run_uid: "batymetry_only"
 
df_run_uid: "hammerhead_v1"
df_dir: "/mnt/data/NatureNet/Hammerhead_Out_v1/"
#No encoder data streams??

n_clusters: 40



