datetimes:
- 09042024T00:00:00Z
- 10042024T00:00:00Z
- 11042024T00:00:00Z
- 12042024T00:00:00Z
- 13042024T00:00:00Z
- 14042024T00:00:00Z
- 15042024T00:00:00Z
- 16042024T00:00:00Z
- 17042024T00:00:00Z
- 18042024T00:00:00Z
- 19042024T00:00:00Z
- 20042024T00:00:00Z
- 21042024T00:00:00Z
- 22042024T00:00:00Z
- 23042024T00:00:00Z
- 24042024T00:00:00Z
- 25042024T00:00:00Z
- 26042024T00:00:00Z
- 27042024T00:00:00Z
- 28042024T00:00:00Z
- 29042024T00:00:00Z
- 30042024T00:00:00Z
- 01052024T00:00:00Z
- 02052024T00:00:00Z
- 03052024T00:00:00Z
- 04052024T00:00:00Z
- 05052024T00:00:00Z
- 06052024T00:00:00Z
- 07052024T00:00:00Z
- 08052024T00:00:00Z
- 09052024T00:00:00Z
- 10052024T00:00:00Z
df_dir: /mnt/data/NatureNet/Hammerhead_Out_v1/
df_run_uid: hammerhead_v1
final_grid_res_deg: 0.027
instruments:
  Bathymetry:
    data_config: ../../config/environment/bathymetry_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    - - /mnt/data/NatureNet_Env/Bath/gebco_2024_sub_ice_n40.0_s20.0_w-100.0_e-60.0_geotiff.tif
    multi_chan: false
    resample_config: ../../config/environment/bathymetry_resample_config.yaml
  Coastal_Dist:
    data_config: ../../config/environment/distance_to_coast.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    - - /mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif
    multi_chan: false
    resample_config: ../../config/environment/distance_to_coast_resample_config.yaml
  SSS:
    data_config: ../../config/environment/sss_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240409T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240410T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240411T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240412T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240413T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240414T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240415T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240416T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240417T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240418T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240419T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240420T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240421T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240422T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240423T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240424T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240425T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240426T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240427T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240428T1200Z_P20250726T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240429T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240430T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240501T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240502T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240503T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240504T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240505T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240506T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240507T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240508T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240509T1200Z_P20250727T0000Z.nc
    - - /mnt/data/NatureNet_Env/SSS/dataset-sss-ssd-rep-daily_20240510T1200Z_P20250727T0000Z.nc
    multi_chan: true
    resample_config: ../../config/environment/sss_resample_config.yaml
  SST:
    data_config: ../../config/environment/sst_data_config.yaml
    filenames:
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240409.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240410.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240411.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240412.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240413.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240414.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240415.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240416.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240417.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240418.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240419.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240420.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240421.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240422.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240423.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240424.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240425.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240426.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240427.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240428.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240429.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240430.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240501.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240502.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240503.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240504.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240505.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240506.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240507.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240508.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240509.nc
    - - /mnt/data/NatureNet_Env/SST/oisst-avhrr-v02r01.20240510.nc
    multi_chan: true
    resample_config: ../../config/environment/sst_resample_config.yaml
n_clusters: 40
out_dir: /mnt/data/NatureNet_Env/output
run_env_gen: true
run_final_env_gen: false
run_uid: simple_env
save_intermediate_maps: false
save_prelim_scene_maps: false
scenes_by_uid: true
update_stats: false
