
low_res:
 data:
  valid_min: -2513.0
  valid_max: 2695.0
  reader_type: "gtiff"
  reader_kwargs:
   no_arg: ''
  geo_reader_type: "gtiff_geo"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: [
"/mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif"
]

  geo_filenames: [
"/mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif"
]

  chan_dim: 2
  geo_coord_dim: 2
  geo_lat_index: 0
  geo_lon_index: 1


high_res:
 data:
  valid_min: 0.0
  valid_max: 100000000
  reader_type: "numpy"
  reader_kwargs:
   no_arg: "no_arg"
  geo_reader_type: "numpy"
  geo_reader_kwargs:
   no_arg: "no_arg"
  filenames: []
  geo_filenames: []
  chan_dim: 0
  geo_coord_dim: 2
  geo_lat_index: 0
  geo_lon_index: 1


fusion:
 projection_id: 4326
 description: "Generating GOES GeoTiffs"
 area_id: "GOES"
 projection_proj4:
  proj: "longlat"
  datum: "WGS84" 
 final_resolution: 0.009000090001 #1km
 projection_units: "degrees"
 resample_radius: 5000
 resample_n_neighbors: 64
 resample_n_procs: 10
 resample_epsilon: 1.6
 use_bilinear: True 
 lon_bounds: [-100.0, -60.0]
 lat_bounds: [20.0, 40.0]

       
output_files: [
"/mnt/data/NatureNet_Env/Coastal_Dist/GMT_intermediate_coast_distance_01d.tif"
]
